Mayhem integration
mayhemheroes/naga pull request #1
Opened 2022-04-24 01:09 UTC by kiranprasad

2022-04-25 03:50 UTC, xansec requested changes

2022-04-25 03:50 UTC, xansec commented on Mayhemfile
> +image: ghcr.io/kiranprasad/naga:latest
There is no need to specify an image here - the image is overwritten in the Mayhem action workflow. Please either remove or comment it out, as this will change once the PR is merged.

2022-04-25 03:50 UTC, xansec commented on Mayhemfile
> +  - cmd: /wgsl_parser
Mayhemfiles only take one command for a target - you have two. Please either remove one of the commands, or create two Mayhemfiles with one target each.

2022-04-25 03:50 UTC, xansec commented on Mayhemfile
> +target: naga
The target name should reflect what is being fuzzed. If, for example, you are fuzzing the `ir` executable, then your target name should be `ir`

2022-04-26 01:07 UTC, kiranprasad reviewed
I've split the mayhem files and updated gh actions for the targets.

2022-04-26 01:14 UTC, xansec commented
Great, LGTM!

2022-04-26 01:14 UTC, xansec approved these changes

2022-04-26 01:14 UTC, merged